name: SonarQube Analysis for C#

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest  # Required for .NET projects

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'  # or your version
    - name: Set up Java 17 for SonarScanner
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Install SonarScanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Add dotnet tools to PATH
      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

    - name: Begin SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: >
        dotnet-sonarscanner begin 
        /k:"first-try" 
        /d:sonar.host.url="${{ env.SONAR_HOST_URL }}" 
        /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Build solution
      run: dotnet build --no-incremental

    - name: End SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  
    - name: Export SonarQube issues to JSON
      shell: pwsh
      run: |
        $auth = "${env:SONAR_TOKEN}:"
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($auth)
        $encodedAuth = [Convert]::ToBase64String($bytes)
        $headers = @{ Authorization = "Basic $encodedAuth" }
        $url = "${env:SONAR_HOST_URL}/api/issues/search?componentKeys=first-try&resolved=false"
        Invoke-RestMethod -Uri $url -Headers $headers -OutFile "sonar-issues.json"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

        
    - name: Upload issues JSON as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sonar-issues
        path: sonar-issues.json
